version: '3'

services:
  mysql:
    image: 'mysql/mysql-server:5.7'
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
      MYSQL_DATABASE: 'multitest'
